name: Deployment

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/main.yml'
      - 'src/**'

  pull_request:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node install
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: install clasp
        run: npm install -g @google/clasp

      # - name: create clasprc.json
      #   run: |
      #     cat << EOS > ~/.clasprc.json
      #     {
      #       "token": {
      #         "access_token": "${{ secrets.ACCESS_TOKEN }}",
      #         "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/script.webapp.deploy openid",
      #         "token_type": "Bearer",
      #         "id_token": "${{ secrets.ID_TOKEN }}",
      #         "expiry_date": 1647313465428,
      #         "refresh_token": "${{ secrets.REFRESH_TOKEN }}"
      #       },
      #       "oauth2ClientSettings": {
      #         "clientId": "${{ secrets.CLIENT_ID }}",
      #         "clientSecret": "${{ secrets.CLIENT_SECRET }}",
      #         "redirectUri": "http://localhost"
      #       },
      #       "isLocalCreds": false
      #     }
      #     EOS

      - name: create ~/.clasprc.json
        run: echo -n '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

      - name: create .clasp.json
        run: |
          echo -n '${{ secrets.CLASP_JSON }}' > .clasp.json

      - name: deploy
        run: clasp push -f
